# {1}
on:
  push:
    branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]

jobs:
  Angular_build:
    name: Angular Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      # {2}
      - name: Checkout the source code
        uses: actions/checkout@v3

      # {3}
      - name: Setup Node.js $
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      # {4}
      - name: Install dependencies
        run: npm install
      # {5}
      - name: Run Lint
        run: npm run lint
      # {6}
      - name: Run tests
        run: npm run test:ci
      # {7}
      - name: Build
        run: npm run build:prod
      # {8}
      - name: Upload artifact  
        uses: actions/upload-artifact@v3
        with:
          name: ci_cd_github-${{ github.run_id }}-${{ github.run_number }}
          path: ./dist/ci_cd_github

jobs:
  Angular_deploy:
    name: Angular Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      # {1} 
      - name: Download artifact  
        uses: actions/download-artifact@v3  
        with:  
          name: ci_cd_github-${{ github.run_id }}-${{ github.run_number }}  
          path: './build'
      # {2}
      - name: Deploy to Netlify  
        uses: nwtgck/actions-netlify@v1.1  
        with:  
          publish-dir: './build'  
          production-branch: main  
          github-token: ${{ secrets.G_TOKEN }}  
          deploy-message: "Deploy from GitHub Actions"  
          enable-pull-request-comment: true  
          enable-commit-comment: true  
          overwrites-pull-request-comment: true  
        env:  
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}  
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}